### ISSUE TITLE
auto_combine fails with error - non-conformable arguments

### ISSUE THREAD

**Issue by chintan-sd** [ceweiss/GeomComb#2]
Code to reproduce the issue:
```
library(fpp2)
library(forecast)
library(ForecastComb)

h=4

ft_e <- ets(austa)
fs_e <- forecast(ft_e, h = h)

ft_a <- auto.arima(austa)
fs_a <- forecast(ft_a, h = h)

train_o <- austa
train_p <- cbind(fs_e$fitted, fs_a$fitted)

test_p <- cbind(fs_e$mean, fs_a$mean)

data <- foreccomb(train_o, train_p, newpreds=test_p)
fit <- auto_combine(data)
```
Error:

```
Error in prediction_matrix %*% weights : non-conformable arguments
In addition: Warning message:
In .cbind.ts(list(e1, e2), c(deparse(substitute(e1))[1L], deparse(substitute(e2))[1L]),  :
  non-intersecting series
```

**Comment by RoetGer** [comment]
Hi,
once again thank you for using our package. The newly pushed version fixes also this issue.

Best regards

**Comment by sagarneelde** [comment]
Hi 
Could you please help me why I'm finding this error

`head(tdata)
                     ds      Target   ModelA   ModelB    ModelC
214 2016-11-04 1.084078 1.147933 1.082057  1.170006
215 2016-11-07 1.126075 1.162783 1.085200  1.180077
216 2016-11-08 1.114221 1.148424 1.082239  1.156795
217 2016-11-09 1.147437 1.163229 1.086117  1.170436
218 2016-11-10 1.201628 1.134066 1.079426  1.137131
219 2016-11-11 1.138494 1.103167 1.070790  1.120262

x <- foreccomb(tdata %>% filter(ds <= last.dev.date) %>% select(Target) %>% as.matrix(),
                          tdata %>% filter(ds <= last.dev.date) %>% select(-c(Target, ds)) %>% as.matrix(),
                          tdata %>% filter(ds > last.dev.date) %>% select(Target) %>% as.matrix(),
                          tdata %>% filter(ds > last.dev.date) %>% select(-c(Target, ds)) %>% as.matrix()
                          )

y <- auto_combine(x)
Error in `-.default`(observed_vector, prediction_matrix) : 
  non-conformable arrays`
